version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key
      - GITHUB_CLIENT_ID=your-github-client-id
      - GITHUB_CLIENT_SECRET=your-github-client-secret
      - DB_TYPE=mysql
      - DB_USER=getshort
      - DB_PASSWORD=getshortpass
      - DB_HOST=db
      - DB_NAME=getshort
      - PORT=8000
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=getshort
      - MYSQL_USER=getshort
      - MYSQL_PASSWORD=getshortpass
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: