apiVersion: v1
kind: Secret
metadata:
  name: getshort-secrets
type: Opaque
data:
  # Generate actual secrets with: echo -n "your-secret" | base64
  secret-key: ${BASE64_SECRET_KEY}
  db-user: ${BASE64_DB_USER}
  db-password: ${BASE64_DB_PASSWORD}
  github-client-id: ${BASE64_GITHUB_CLIENT_ID}
  github-client-secret: ${BASE64_GITHUB_CLIENT_SECRET}